on: workflow_dispatch

name: 🚀 Production Build and Deploy

jobs:
  build-and-deploy:
    name: 🎉 Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get code
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Fetch LFS assets
        run: git lfs checkout

      - name: Use Node.js 16.18.1
        uses: actions/setup-node@v2-beta
        with:
          node-version: "16.18.1"

      - name: Create env file
        run: |
          touch .env
          echo REACT_APP_ANALYTICS_TRACKING_ID=${{ secrets.REACT_APP_ANALYTICS_TRACKING_ID }} >> .env
          echo REACT_APP_DATOCMS_API_TOKEN=${{ secrets.REACT_APP_DATOCMS_API_TOKEN }} >> .env
          cat .env

      - name: 🔨 Build Project
        run: |
          yarn
          yarn build

      - name: 📂 Upload files
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          SOURCE: "public/"
          REMOTE_HOST: "h81.seohost.pl"
          REMOTE_PORT: "57185"
          REMOTE_USER: "srv116488"
          TARGET: "/home/srv116488/domains/igorpatro.com/public_html"
